### ISSUE TITLE
Unable to build on aarch64

### ISSUE THREAD

**Issue by Shatur** [rust-skia/rust-skia#535] opened 2021-06-27 22:12 UTC
Hi! I building this library as a part of this project: https://github.com/Kethku/neovide

And I have the following build error:

```
error: failed to run custom build command for `skia-bindings v0.39.1`

Caused by:
  process didn't exit successfully: `/home/shatur/.cache/paru/clone/neovide-git/src/neovide-git/target/release/build/skia-bindings-caba516915705bd9/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-env-changed=SKIA_DEBUG
  HOST: aarch64-unknown-linux-gnu
  cargo:rerun-if-env-changed=OPT_LEVEL
  cargo:rerun-if-env-changed=CC
  cargo:rerun-if-env-changed=CXX
  cargo:rerun-if-env-changed=SKIA_SOURCE_DIR
  cargo:rerun-if-env-changed=FORCE_SKIA_BUILD
  cargo:rerun-if-env-changed=FORCE_SKIA_BINARIES_DOWNLOAD
  TRYING TO DOWNLOAD AND INSTALL SKIA BINARIES: 0.39.1/750688025ba50471efe8-aarch64-unknown-linux-gnu-gl
  cargo:rerun-if-env-changed=SKIA_BINARIES_URL
    FROM: https://github.com/rust-skia/skia-binaries/releases/download/0.39.1/skia-binaries-750688025ba50471efe8-aarch64-unknown-linux-gnu-gl.tar.gz
  DOWNLOAD AND INSTALL FAILED: https://github.com/rust-skia/skia-binaries/releases/download/0.39.1/skia-binaries-750688025ba50471efe8-aarch64-unknown-linux-gnu-gl.tar.gz: status code 404
  STARTING A FULL BUILD
  cargo:rerun-if-env-changed=SKIA_USE_SYSTEM_LIBRARIES
  cargo:rerun-if-env-changed=SDKROOT
  cargo:rerun-if-env-changed=SKIA_NINJA_COMMAND
  cargo:rerun-if-env-changed=SKIA_GN_COMMAND
  Probing 'python'
  Probing 'python2'
  Python 2 found: "python2"
  Synchronizing Skia dependencies
  DOWNLOADING: https://codeload.github.com/rust-skia/skia/tar.gz/m90-0.38.3
  DOWNLOADING: https://codeload.github.com/rust-skia/depot_tools/tar.gz/a110bf6
  Skipping "../src".
  skia/third_party/externals/libgif... > fd59fa92a0c86788dcdd84d091e1ce81eda06a77
  skia/third_party/externals/piex      > bb217acdca1cc0c16b704669dd6f91a1b509c406
  skia/third_party/externals/d3d12a... > 169895d529dfce00390a20e69c2f516066fe7a3b
  skia/third_party/externals/zlib      > c876c8f87101c5a75f6014b0f832499afeb65b73
  skia/third_party/externals/libjpe... > 64fc43d52351ed52143208ce6a656c03db56462b
  skia/third_party/externals/libwebp   > fedac6cc69cda3e9e04b780d324cf03921fb3ff4
  skia/third_party/externals/expat     > e976867fb57a0cd87e3b0fe05d59e0ed63c6febb
  skia/third_party/externals/spirv-... > bdbef7b1f3982fe99a62d076043036abe6dd6d80
  skia/third_party/externals/harfbuzz  > 3a74ee528255cc027d84b204a87b5c25e47bff79
  skia/third_party/externals/freetype  > dfa7cca5f3b4f494aae785891ab4a42e66db77ef
  skia/third_party/externals/libpng    > 386707c6d19b974ca2e3db7f5c61873813c6fe44
  skia/third_party/externals/icu       > dbd3825b31041d782c5b504c59dcfb5ac7dda08c

  --- stderr
  Traceback (most recent call last):
    File "skia/bin/fetch-gn", line 26, in <module>
      cpu = {'amd64': 'amd64', 'arm64': 'arm64', 'x86_64': 'amd64'}[platform.machine().lower()]
  KeyError: 'aarch64'
  Traceback (most recent call last):
    File "skia/tools/git-sync-deps", line 266, in <module>
      exit(main(sys.argv[1:]))
    File "skia/tools/git-sync-deps", line 261, in main
      os.path.join(os.path.dirname(deps_file_path), 'bin', 'fetch-gn')])
    File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['/usr/bin/python2', 'skia/bin/fetch-gn']' returned non-zero exit status 1
  thread 'main' panicked at '`skia/tools/git-sync-deps` failed', /home/shatur/.cache/paru/clone/neovide-git/src/neovide-git/CARGO/registry/src/github.com-1ecc6299db9ec823/skia-bindings-0.39.1/build_support/skia.rs:630:9
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I reported it in https://github.com/Kethku/neovide/issues/766 first, but the author said that this is a library issue.

**Comment by pragmatrix** [comment] 2021-06-28 09:48
I'm trying to build a Dockerfile and run it with Qemu aarch64 emulation to reproduce this first. Perhaps this is easy to fix by patching the fetch-gn script.

**Comment by pragmatrix** [comment] 2021-06-28 12:29
I've [patched the fetch-gn](https://github.com/rust-skia/skia/compare/74276ea938c607ceeebad2812d20189f0eb48adb...89eb532d06592409d4af7d2683212aa0c9e0e32a#diff-678a7e922b751b8cefb974e892e4fd1340e4bbcecad9aa051839186aea88c92fR26) and also update Skia in #536.

Also added a [`Dockerfile`](https://github.com/pragmatrix/rust-skia/blob/support-aarch64-linux-hosts/docker/linux/aarch64/Dockerfile) that "seems" to build. "Seems", because it took so long that I had to interrupt it. But at that time the Skia build and the binding generation step were both successful.

Please try to see if you can build the branch in #536. You need to set `SKIA_NINJA_COMMAND=/usr/bin/ninja` (`ninja` can be be installed with `apt-get install ninja.build`).

**Comment by Shatur** [comment] 2021-06-28 13:31
@pragmatrix, thiank you! But what commands should I use to build it? I'm not familiar with Rust :)

**Comment by pragmatrix** [comment] 2021-06-28 13:48
With Docker Desktop on Windows I was able to build the branch it inside a arm64 container with `cargo build --features "gl" -vv`.

**Comment by Shatur** [comment] 2021-06-28 16:51
@pragmatrix, yes, i successfully compiled it!

**Comment by pragmatrix** [comment] 2021-07-02 07:20
I've just released the updated version. If not done already, the next step would be see if Neovide can be updated to use version 0.40.2 https://github.com/rust-skia/rust-skia/releases/tag/0.40.2

Closing.

**Closed by pragmatrix** 2021-07-02 07:20 UTC
Labels: bug, build

**Comment by Shatur** [comment] 2021-07-06 11:38
@pragmatrix This is weird, but I can't compile the 0.40.2. Now I have the following error:

```
error: failed to run custom build command for `skia-bindings v0.40.2`

Caused by:
  process didn't exit successfully: `/home/shatur/.cache/paru/clone/neovide-git/src/neovide-git/target/release/build/skia-bindings-b8f20ecfe6d564fb/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-env-changed=SKIA_DEBUG
  cargo:rerun-if-env-changed=SKIA_SOURCE_DIR
  cargo:rerun-if-env-changed=FORCE_SKIA_BUILD
  cargo:rerun-if-env-changed=FORCE_SKIA_BINARIES_DOWNLOAD
  TRYING TO DOWNLOAD AND INSTALL SKIA BINARIES: 0.40.2/5c96670703e06e64f6fd-aarch64-unknown-linux-gnu-gl
  cargo:rerun-if-env-changed=SKIA_BINARIES_URL
    FROM: https://github.com/rust-skia/skia-binaries/releases/download/0.40.2/skia-binaries-5c96670703e06e64f6fd-aarch64-unknown-linux-gnu-gl.tar.gz
  DOWNLOAD AND INSTALL FAILED: https://github.com/rust-skia/skia-binaries/releases/download/0.40.2/skia-binaries-5c96670703e06e64f6fd-aarch64-unknown-linux-gnu-gl.tar.gz: status code 404
  STARTING A FULL BUILD
  HOST: aarch64-unknown-linux-gnu
  cargo:rerun-if-env-changed=OPT_LEVEL
  cargo:rerun-if-env-changed=CC
  cargo:rerun-if-env-changed=CXX
  cargo:rerun-if-env-changed=SKIA_USE_SYSTEM_LIBRARIES
  cargo:rerun-if-env-changed=SDKROOT
  cargo:rerun-if-env-changed=SKIA_NINJA_COMMAND
  cargo:rerun-if-env-changed=SKIA_GN_COMMAND
  Probing 'python'
  Probing 'python2'
  Python 2 found: "python2"
  Synchronizing Skia dependencies
  DOWNLOADING: https://codeload.github.com/rust-skia/skia/tar.gz/m91-0.39.4
  DOWNLOADING: https://codeload.github.com/rust-skia/depot_tools/tar.gz/fade894
  Skipping "../src".
  skia/third_party/externals/libgif... > fd59fa92a0c86788dcdd84d091e1ce81eda06a77
  skia/third_party/externals/piex      > bb217acdca1cc0c16b704669dd6f91a1b509c406
  skia/third_party/externals/zlib      > c876c8f87101c5a75f6014b0f832499afeb65b73
  skia/third_party/externals/libjpe... > 64fc43d52351ed52143208ce6a656c03db56462b
  skia/third_party/externals/spirv-... > bdbef7b1f3982fe99a62d076043036abe6dd6d80
  skia/third_party/externals/libwebp   > fedac6cc69cda3e9e04b780d324cf03921fb3ff4
  skia/third_party/externals/harfbuzz  > 3a74ee528255cc027d84b204a87b5c25e47bff79
  skia/third_party/externals/d3d12a... > 169895d529dfce00390a20e69c2f516066fe7a3b
  skia/third_party/externals/freetype  > dfa7cca5f3b4f494aae785891ab4a42e66db77ef
  skia/third_party/externals/expat     > e976867fb57a0cd87e3b0fe05d59e0ed63c6febb
  skia/third_party/externals/libpng    > 386707c6d19b974ca2e3db7f5c61873813c6fe44
  skia/third_party/externals/icu       > dbd3825b31041d782c5b504c59dcfb5ac7dda08c
  Skia args: is_official_build=true is_debug=false skia_enable_gpu=true skia_use_gl=true skia_use_egl=false skia_use_x11=false skia_use_system_libpng=false skia_use_libwebp_encode=false skia_use_libwebp_decode=false skia_use_system_zlib=false skia_use_xps=false skia_use_dng_sdk=false cc="clang" cxx="clang++" skia_use_icu=false skia_use_system_libjpeg_turbo=false target_os="linux" target_cpu="arm64" skia_use_expat=true skia_use_system_expat=false extra_cflags=["-O3","--target=aarch64-unknown-linux-gnu"] extra_asmflags=["--target=aarch64-unknown-linux-gnu"]
  Done. Made 76 targets from 28 files in 601ms
  Unknown architecture (aarch64) -- unable to run ninja.
  No prebuilt ninja binary was found for this system.
  Try building your own binary by doing:
    cd ~
    git clone https://github.com/ninja-build/ninja.git -b v1.8.2
    cd ninja && ./configure.py --bootstrap
  Then add ~/ninja/ to your PATH.

  --- stderr
  thread 'main' panicked at '`ninja` returned an error, please check the output for details.', /home/shatur/.cache/paru/clone/neovide-git/src/neovide-git/CARGO/registry/src/github.com-1ecc6299db9ec823/skia-bindings-0.40.2/build_support/skia/config.rs:385:5
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by pragmatrix** [comment] 2021-07-06 12:21
@Shator Did you set the env var `SKIA_NINJA_COMMAND` to `/usr/bin/ninja` or whatever `which ninja` says?

**Comment by Shatur** [comment] 2021-07-06 14:44
> Did you set the env var SKIA_NINJA_COMMAND to /usr/bin/ninja or whatever which ninja says?
`/usr/bin/ninja`

Oh, right, thank you, just forgot about it.
