### ISSUE TITLE
Text no longer rendering on Windows as of 0.42.0

### ISSUE THREAD

**Issue by samizdatco** [rust-skia/rust-skia#565] opened 2021-09-21 13:45 UTC
I'm not sure whether this stems from the newly added `embed-icudtl` feature or something upstream, but as of release 0.42 `Paragraph`-based typesetting no longer produces any output on Windows systems. Everything still seems to be working fine on Linux and macOS, but on Windows it silently fails without reporting any errors in the process.

Here is the [test case](https://github.com/samizdatco/skia-canvas-binaries/blob/f0d3326cb59ac584b9195b9cee2a54d4236d6e5c/src/main.rs) I've been running (which is adapted from the `skia-org/skparagraph_example.rs` example). The platform-by-platform results when run against version 0.42.0 can be seen in [these artifacts](https://github.com/samizdatco/skia-canvas-binaries/suites/3829010090/artifacts/94814305) produced during [this run](https://github.com/samizdatco/skia-canvas-binaries/actions/runs/1257799144).

By comparison, when the same `main.rs` is [run](https://github.com/samizdatco/skia-canvas-binaries/actions/runs/1257825723) against version 0.41.0, it produces the [expected output](https://github.com/samizdatco/skia-canvas-binaries/suites/3829100514/artifacts/94817514).

**Comment by pragmatrix** [comment] 2021-09-22 05:01
Thank you a lot. I can confirm that, this is also visible in the Artifacts generated on the CI. Will add an additional pre-release step before release to visually verify them. The breaking commit is bef9f911c01f7c9503815d6cb665c82d82f07113. Preparing a new release today.

**Comment by pragmatrix** [comment] 2021-09-23 01:47
There were problems with three Linux binary submissions. Will release anyway hoping that a re-run uploads the missing artifacts.

**Comment by pragmatrix** [comment] 2021-09-23 02:02
The release is on crates.io: https://github.com/rust-skia/rust-skia/releases/tag/0.42.1 Closing

**Comment by pragmatrix** [comment] 2021-10-19 10:26
I opt for the latter. I also need to take a closer look how to fix #566, there are some scary things happening at static initialization time which may or may not related. Reopening.

**Comment by pragmatrix** [comment] 2021-11-06 16:51
I can't reproduce this with the current master and Rust 1.56.1. I've added 

```toml
[profile.release]
lto = "fat"
```

to the workspace `Cargo.toml`, removed all `icu::init()` invocations in the skia-org project (will PR soon), and then ran

```cargo run --release -vv --features textlayout```

and the generated text renderings in `cpu/` look fine. 

Would appreciate a minimal repro.

**Comment by pragmatrix** [comment] 2021-11-06 17:16
I can reproduce it now, not sure what happened before.

**Comment by pragmatrix** [comment] 2021-11-06 18:25
3050b3f87946d9e1f8fb13725efd59e4dee97e3a fixed it. Not sure why, I've always though that this makes no difference because `include_bytes!` must include the binary data at compile time, but there is probably something different about the reference that is returned in terms of LTO.

**Closed** 2021-11-06 20:15 UTC
Labels: bug
