### ISSUE TITLE
Windows - Support for -Clink-dead-code

### ISSUE THREAD

**Issue by chichid** [rust-skia/rust-skia#318] opened 2020-04-19 05:14 UTC
I have to enable the -Clink-dead-code in order to generate code coverage for one of my projects. However, there seems to be a problem coming from skia-safe when linking with that flag. I'm following the instructions provided by [grcov](https://github.com/mozilla/grcov). I'm able to build correctly if I remove that flag.

**Build command**
```
export CARGO_INCREMENTAL=0
export RUSTFLAGS="-Zprofile -Ccodegen-units=1 -Copt-level=0 -Clink-dead-code -Coverflow-checks=off -Zno-landing-pads"
cargo build
cargo test
```

**Example of linking errors**
```
"public: void __cdecl SkString::`vbase destructor'(void)" (??_DSkString@@QEAAXXZ) referenced in function _ZN13skia_bindings8bindings8SkString8destruct17h2e
8082931f49dff6E libskia_bindings-9d5bde54cbd3a647.rlib(skia_bindings-9d5bde54cbd3a647.skia_bindings.4thq6d2u-cgu.0.rcgu.o) : error LNK2019: unresolved external symbol "public: void __cdecl SkDeque::`vbase destructor'(void)" (??_DSkDeque@@QEAAXXZ) referenced in function _ZN13skia_bindings8bindings7SkDeque8destruct17haf8c3
c3ff4355596E libskia_bindings-9d5bde54cbd3a647.rlib(skia_bindings-9d5bde54cbd3a647.skia_bindings.4thq6d2u-cgu.0.rcgu.o) : error LNK2019: unresolved external symbol "public: void __cdecl SkPaint::`vbase destructor'(void)" (??_DSkPaint@@QEAAXXZ) referenced in function _ZN13skia_bindings8bindings7SkPaint8destruct17h43ebe
74856ac54bfE
```

**Generated linker command:**
```
error: linking with `link.exe` failed: exit code: 1120 |
  = note: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.23.28105\\bin\\HostX64\\x64\\link.exe" "/NOLOGO" "/NXCOMPAT" "/LIBPATH:C:\\Users\\rachidox\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib" "C:\\Users\\rachidox\\Home\\g
ithub\\universe-skia-poc\\skia-safe-poc\\target\\debug\\deps\\skia_safe_poc-a06c1188f6c2379f.skia_safe_poc.4wof72ks-cgu.0.rcgu.o" "/OUT:C:\\Users\\rachidox\\H
ome\\github\\universe-skia-poc\\skia-safe-poc\\target\\debug\\deps\\skia_safe_poc-a06c1188f6c2379f.exe" "/DEBUG" "/NATVIS:C:\\Users\\rachidox\\.rustup\\toolch
ains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\intrinsic.natvis" "/NATVIS:C:\\Users\\rachidox\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\
lib\\rustlib\\etc\\liballoc.natvis" "/NATVIS:C:\\Users\\rachidox\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\libcore.natvis" "/NA
TVIS:C:\\Users\\rachidox\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\libstd.natvis" "/LIBPATH:C:\\Users\\rachidox\\Home\\github\\
universe-skia-poc\\skia-safe-poc\\target\\debug\\deps" "/LIBPATH:C:\\Users\\rachidox\\Home\\github\\universe-skia-poc\\skia-safe-poc\\target\\debug\\build\\skia-bindings-31807756e9d02dd6\\out\\skia" "/LIBPATH:C:\\Users\\rachidox\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-m
svc\\lib" "/LIBPATH:C:\\Users\\rachidox\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib" "test-16d7664c2b987d4
5.dll.lib" "C:\\Users\\rachidox\\Home\\github\\universe-skia-poc\\skia-safe-poc\\target\\debug\\deps\\libskia_safe-7af3055b17345ac2.rlib" "C:\\Users\\rachidox
\\Home\\github\\universe-skia-poc\\skia-safe-poc\\target\\debug\\deps\\libskia_bindings-9d5bde54cbd3a647.rlib" "C:\\Users\\rachidox\\Home\\github\\universe-sk
ia-poc\\skia-safe-poc\\target\\debug\\deps\\liblazy_static-03a16b23802d8762.rlib" "C:\\Users\\rachidox\\Home\\github\\universe-skia-poc\\skia-safe-poc\\target
\\debug\\deps\\libbitflags-e9b503ab5e675abc.rlib" "C:\\Users\\rachidox\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libprofiler_builtins-d6f4b4bfe2d2890a.rlib" "/LIBPATH:C:\\Users\\rachidox\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64
-pc-windows-msvc\\lib" "std-597c5a05d736e633.dll.lib" "C:\\Users\\rachidox\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libcompiler_builtins-94f7006c25e00caf.rlib" "kernel32.lib" "usp10.lib" "ole32.lib" "user32.lib" "gdi32.lib" "fontsub.lib" "advapi32.lib" "ws2_32
.lib" "userenv.lib" "msvcrt.lib"
  = note: libskia_bindings-9d5bde54cbd3a647.rlib(skia_bindings-9d5bde54cbd3a647.skia_bindings.4thq6d2u-cgu.0.rcgu.o) : error LNK2019: unresolved external symb
ol "public: void __cdecl SkString::`vbase destructor'(void)" (??_DSkString@@QEAAXXZ) referenced in function _ZN13skia_bindings8bindings8SkString8destruct17h2e
8082931f49dff6E
          libskia_bindings-9d5bde54cbd3a647.rlib(skia_bindings-9d5bde54cbd3a647.skia_bindings.4thq6d2u-cgu.0.rcgu.o) : error LNK2019: unresolved external symb
ol "public: void __cdecl SkDeque::`vbase destructor'(void)" (??_DSkDeque@@QEAAXXZ) referenced in function _ZN13skia_bindings8bindings7SkDeque8destruct17haf8c3
c3ff4355596E
```

**Comment by pragmatrix** [comment] 2020-04-19 13:33
I am assuming this could be related to https://github.com/rust-lang/rust-bindgen/issues/1725 because I had similar linker errors when I called these destructors that were generated with bingen. I'll try to see if there is a workaround....

**Comment by pragmatrix** [comment] 2020-04-19 16:11
Took a while to find workarounds for the different situations that caused linker errors, but I think I'm on the right track with #321.

**Comment by chichid** [comment] 2020-04-19 17:20
Thanks for this great Crate. Actually I tried to link against the fix branch, there are less issues however I still see these:
```
note: libskia_bindings-6f59f90af691f8cb.rlib(skia_bindings-6f59f90af691f8cb.skia_bindings.9uzl4pl8-cgu.0.rcgu.o) : error LNK2019: unresolved exter
nal symbol "public: class SkDeferredDisplayListPriv __cdecl SkDeferredDisplayList::priv(void)" (?priv@SkDeferredDisplayList@@QEAA?AVSkDeferredDisplayL
istPriv@@XZ) referenced in function _ZN13skia_bindings8bindings21SkDeferredDisplayList5priv_17heedb8d99ab718c63E
          libskia_bindings-6f59f90af691f8cb.rlib(skia_bindings-6f59f90af691f8cb.skia_bindings.9uzl4pl8-cgu.0.rcgu.o) : error LNK2019: unresolved exter
nal symbol "public: class SkDeferredDisplayListPriv const __cdecl SkDeferredDisplayList::priv(void)const " (?priv@SkDeferredDisplayList@@QEBA?BVSkDefe
rredDisplayListPriv@@XZ) referenced in function _ZN13skia_bindings8bindings21SkDeferredDisplayList5priv117h29bba020676b96d9E
          libskia_bindings-6f59f90af691f8cb.rlib(skia_bindings-6f59f90af691f8cb.skia_bindings.9uzl4pl8-cgu.0.rcgu.o) : error LNK2019: unresolved exter
nal symbol "public: static class sk_sp<class SkImage> __cdecl SkImage::MakeTextureFromCompressed(class GrContext *,class sk_sp<class SkData>,int,int,e
num SkImage::CompressionType,enum GrMipMapped,enum GrProtected)" (?MakeTextureFromCompressed@SkImage@@SA?AV?$sk_sp@VSkImage@@@@PEAVGrContext@@V?$sk_sp
@VSkData@@@@HHW4CompressionType@1@W4GrMipMapped@@W4GrProtected@@@Z) referenced in function _ZN13skia_bindings8bindings7SkImage25MakeTextureFromCompres
sed17h211737b4cf3addd3E
          libskia_bindings-6f59f90af691f8cb.rlib(skia_bindings-6f59f90af691f8cb.skia_bindings.9uzl4pl8-cgu.0.rcgu.o) : error LNK2019: unresolved exter
nal symbol "public: static class sk_sp<class SkImage> __cdecl SkImage::MakeCrossContextFromPixmap(class GrContext *,class SkPixmap const &,bool,bool)"
 (?MakeCrossContextFromPixmap@SkImage@@SA?AV?$sk_sp@VSkImage@@@@PEAVGrContext@@AEBVSkPixmap@@_N2@Z) referenced in function _ZN13skia_bindings8bindings
7SkImage26MakeCrossContextFromPixmap17hbbb63a1fd4168b0bE
          libskia_bindings-6f59f90af691f8cb.rlib(skia_bindings-6f59f90af691f8cb.skia_bindings.9uzl4pl8-cgu.0.rcgu.o) : error LNK2019: unresolved exter
nal symbol "public: static class sk_sp<class SkImage> __cdecl SkImage::MakeFromYUVATextures(class GrContext *,enum SkYUVColorSpace,class GrBackendText
ure const * const,struct SkYUVAIndex const * const,struct SkISize,enum GrSurfaceOrigin,class sk_sp<class SkColorSpace>)" (?MakeFromYUVATextures@SkImag
e@@SA?AV?$sk_sp@VSkImage@@@@PEAVGrContext@@W4SkYUVColorSpace@@QEBVGrBackendTexture@@QEBUSkYUVAIndex@@USkISize@@W4GrSurfaceOrigin@@V?$sk_sp@VSkColorSpa
ce@@@@@Z) referenced in function _ZN13skia_bindings8bindings7SkImage20MakeFromYUVATextures17hf8af6dad6955c7e0E
          libskia_bindings-6f59f90af691f8cb.rlib(skia_bindings-6f59f90af691f8cb.skia_bindings.9uzl4pl8-cgu.0.rcgu.o) : error LNK2019: unresolved exter
nal symbol "public: static class sk_sp<class SkImage> __cdecl SkImage::MakeFromYUVAPixmaps(class GrContext *,enum SkYUVColorSpace,class SkPixmap const
 * const,struct SkYUVAIndex const * const,struct SkISize,enum GrSurfaceOrigin,bool,bool,class sk_sp<class SkColorSpace>)" (?MakeFromYUVAPixmaps@SkImag
e@@SA?AV?$sk_sp@VSkImage@@@@PEAVGrContext@@W4SkYUVColorSpace@@QEBVSkPixmap@@QEBUSkYUVAIndex@@USkISize@@W4GrSurfaceOrigin@@_N6V?$sk_sp@VSkColorSpace@@@
@@Z) referenced in function _ZN13skia_bindings8bindings7SkImage19MakeFromYUVAPixmaps17hb278117b416493a1E
          libskia_bindings-6f59f90af691f8cb.rlib(skia_bindings-6f59f90af691f8cb.skia_bindings.9uzl4pl8-cgu.0.rcgu.o) : error LNK2019: unresolved exter
nal symbol "public: static class sk_sp<class SkSurface> __cdecl SkSurface::MakeFromBackendTexture(class GrContext *,class SkSurfaceCharacterization co
nst &,class GrBackendTexture const &,void (__cdecl*)(void *),void *)" (?MakeFromBackendTexture@SkSurface@@SA?AV?$sk_sp@VSkSurface@@@@PEAVGrContext@@AE
BVSkSurfaceCharacterization@@AEBVGrBackendTexture@@P6AXPEAX@Z3@Z) referenced in function _ZN13skia_bindings8bindings9SkSurface23MakeFromBackendTexture
117hf9f408d833e946eaE
          C:\Users\rachidox\Home\github\universe-skia-poc\skia-safe-poc\target\debug\deps\skia_safe_poc-a62f84347b29b927.exe : fatal error LNK1120: 7
unresolved externals
```

**Comment by j4qfrost** [comment] 2020-04-25 09:27
Also trying to use grcov. I'm running into this issue with a Mac specific crate. Are there any docs that can help me attempt a fix or help out?

**Comment by pragmatrix** [comment] 2020-04-25 10:10
The `SkDeferredDisplayList::priv` linker error were just for me to test if the CI marks them as errors (which it didn't for some reason), I've [uncommented these lines](https://github.com/pragmatrix/rust-skia/blob/link-dead-code/skia-bindings/build_support/skia.rs#L584-L586), so you might try again if that were the only linker errors left. 

For the remaining linker errors that appeared in @chichid's log, I've no explanation yet and need to see if I am even able to reproduce them.

My strategy for preventing the linker errors is to remove the functions from the generated bindings by blacklisting them and generating stubs if needed. For the ones that are needed in skia-safe I would create a wrapper with a signature for which the binding generation works.

**Comment by pragmatrix** [comment] 2020-04-26 12:52
Here an update about the linker errors I was able to reproduce:

Compiling with:
```bash
export CARGO_INCREMENTAL=0
export RUSTFLAGS="-Ccodegen-units=1 -Copt-level=0 -Clink-dead-code -Coverflow-checks=off"
cargo build -vv
```


the Windows build with the Branch `link-dead-code` (with all features enabled, "gl", "vulkan", and "textlayout") works so without any linker errors. But I had no luck to generate the bindings with the nightly compiler, somehow the binding generation just stops.

The macOS (LLVM 10) build with all features (the ones above + "metal") fails to link with one linker error:

```
  = note: Undefined symbols for architecture x86_64:
            "_CFMutableAttributedStringGetTypeID", referenced from:
                _$LT$core_foundation..attributed_string..CFMutableAttributedString$u20$as$u20$core_foundation..base..TCFType$GT$::type_id::h2bbb20d9af45e39f in libcore_foundation-4b8d866b003bda1a.rlib(core_foundation-4b8d866b003bda1a.core_foundation.7u55rrq4-cgu.0.rcgu.o)
                _$LT$core_foundation..attributed_string..CFMutableAttributedString$u20$as$u20$core_foundation..base..TCFType$GT$::type_id::h7a7d878dcafc09fc in libcore_foundation-62a6a57942bad80d.rlib(core_foundation-62a6a57942bad80d.core_foundation.en1q3mex-cgu.0.rcgu.o)
          ld: symbol(s) not found for architecture x86_64
```
which is probably related to [this issue](https://github.com/servo/core-foundation-rs/pull/357) but may not happen with other executables built with skia-safe.

I am considering to merge the branch as "better than before" and close this issue because there is currently no action I am able to proceed with. Please reopen or create a new issue if new information comes up.

**Closed** 2020-04-26 12:53 UTC
Labels: bug, build

**Comment by j4qfrost** [comment] 2020-04-27 01:53
I was able to get rid of one of the _CFMutableAttributedStringGetTypeID errors by locally updating the core-foundations dependency in winit. I'll try to look for another reference for this and update the thread.

**Comment by j4qfrost** [comment] 2020-04-27 03:30
Enabling mac_os_10_8_features works.
