### ISSUE TITLE
Please provide prebuilt binary for aarch64-unknown-linux-gnu

### ISSUE THREAD

**Issue by zhengcan** [rust-skia/rust-skia#756] opened 2023-01-15 08:27 UTC
Hi

I'm try to use rust-skia under aarch64-unknown-linux-gnu.
Without prebuilt binary of skia, it's really slow to build my apps.
Please provide the prebuilt binary to it, thanks.

**Comment by pragmatrix** [comment] 2023-01-15 20:19
Sure, what feature set do you need? Available are: gl,egl,x11,wayland,vulkan,textlayout,svg,webp.

**Comment by zhengcan** [comment] 2023-01-16 07:42
I'd like to use: gl, textlayout, svg, webp.

**Comment by ctrlcctrlv** [comment] 2023-03-02 06:31
This may not have all the features you need, I'm not sure, I know it at least has svg: 
[skia-bindings-aarch64-unknown-linux-gnu-20220302.tar.gz](https://github.com/rust-skia/rust-skia/files/10868251/skia-bindings-aarch64-unknown-linux-gnu-20220302.tar.gz)

I'm only uploading it because compiling it wasn't easy :-)

**Comment by ctrlcctrlv** [comment] 2023-03-14 01:48
Don't forget to close this @pragmatrix :)

**Comment by pragmatrix** [comment] 2023-03-14 09:26
Thanks, but I am trying to get the CI to cross compile aarch64 binaries and deploy them to the skia-binaries repository in #757. So far I am a bit out of luck, because cross compiling on Ubuntu does not seem easy as you might noticed. If you cross-compiled from a Intel or AMD machine, you could help by listing the needed packages / configurations (so far we are stuck on Ubuntu 18 on the CI (gcc 9, llvm 9), because of libc incompatibilities), see also the https://github.com/pragmatrix/rust-skia-containers repository. I'll try later today to reproduce the CI environment on one of my Intel machines using Docker.

**Comment by ctrlcctrlv** [comment] 2023-03-15 00:06
I looked into running a custom Actions for this. I need them for MFEK too. Might be a way we can collaborate, a private ci.mfek.org that you can use as much as you want and which I'll use too for building Mac stuff.

**Comment by Jhonfunk** [comment] 2023-12-09 20:31
Hopefully rust-skia perfects recompiling from source instead of providing a pre-built version. For example, in android not only to distinguish the hardware architecture, but also the NDK platforms (also known as NDK API level). Providing android pre-built version is poorly adapted.  #892

**Closed** 2024-01-17 19:11 UTC
