### ISSUE TITLE
python3 is not recognized while being installed and successfully probed on Windows 10

### ISSUE THREAD

**Issue by syrel** [rust-skia/rust-skia#657] opened 2022-07-09 09:34 UTC
Hi

When building `rust-skia` on Windows 10 with `textlayout` feature enabled the build fails with `'python3' is not recognized` error.
However, `Python 3` was successfully detected during the init step:
```
Probing 'python'
Python 3 found: "python"
...
FAILED: icudtl.dat
cmd.exe /c  python3 "skia-bindings/skia/gn/cp.py" skia-bindings/skia/third_party/externals/icu/common/icudtl.dat icudtl.dat
'python3' is not recognized as an internal or external command, operable program or batch file.
```

Python3 was installed using `choco install -y python3`. The distribution is shipped with `python.exe` executable.
Copy pasting `python.exe` as `python3.exe` fixed the problem.

I wonder though, where in the build scripts does ninja decide to use `python3` executable instead of `python`? Any ideas?

```
where python
C:\Python310\python.exe
```

Full log including Skia args:
```
Caused by:
  process didn't exit successfully: `C:\j\skia\target\release\build\skia-bindings-34ff08ec2b8efddb\build-script-build` (exit code: 101)
  --- stdout
  cargo:rerun-if-env-changed=SKIA_DEBUG
  cargo:rerun-if-env-changed=SKIA_SOURCE_DIR
  cargo:rerun-if-env-changed=FORCE_SKIA_BUILD
  cargo:rerun-if-env-changed=FORCE_SKIA_BINARIES_DOWNLOAD
  STARTING A FULL BUILD
  HOST: x86_64-pc-windows-msvc
  cargo:rerun-if-env-changed=OPT_LEVEL
  cargo:rerun-if-env-changed=CC
  cargo:rerun-if-env-changed=CXX
  cargo:rerun-if-env-changed=SKIA_USE_SYSTEM_LIBRARIES
  cargo:rerun-if-env-changed=SDKROOT
  cargo:rerun-if-env-changed=VCINSTALLDIR
  cargo:rerun-if-env-changed=LLVM_HOME
  cargo:rerun-if-env-changed=SKIA_NINJA_COMMAND
  cargo:rerun-if-env-changed=SKIA_GN_COMMAND
  Probing 'python'
  Python 3 found: "python"
  Synchronizing Skia dependencies
  Skipping "bin".
  skia\third_party/externals/brotli    @ e61745a6b7add50d380cfd7d3883dd6c62fc2c71
  ...rd_party/externals/d3d12allocator @ 169895d529dfce00390a20e69c2f516066fe7a3b
  skia\third_party/externals/expat     @ a28238bdeebc087071777001245df1876a11f5ee
  skia\third_party/externals/freetype  @ a8e4563c3418ed74d39019a6c5e2122d12c8f56f
  ...ird_party/externals/libjpeg-turbo @ 22f1a22c99e9dde8cd3c72ead333f425c5a7aa77
  skia\third_party/externals/libwebp   @ 20ef03ee351d4ff03fc5ff3ec4804a879d1b9d5c
  skia\third_party/externals/harfbuzz  @ 8d1b000a3edc90c12267b836b4ef3f81c0e53edc
  skia\third_party/externals/piex      @ bb217acdca1cc0c16b704669dd6f91a1b509c406
  ...third_party/externals/libgifcodec @ fd59fa92a0c86788dcdd84d091e1ce81eda06a77
  ...y/externals/vulkanmemoryallocator @ 7de5cc00de50e71a3aab22dea52fbb7ff4efceb6
  skia\third_party/externals/libpng    @ 386707c6d19b974ca2e3db7f5c61873813c6fe44
  skia\third_party/externals/wuffs     @ 600cd96cf47788ee3a74b40a6028b035c9fd6a61
  skia\third_party/externals/zlib      @ c876c8f87101c5a75f6014b0f832499afeb65b73
  ...third_party/externals/spirv-cross @ 940efca099afd08bf9ef1679239b5040976d2cb2
  skia\third_party/externals/icu       @ a0718d4f121727e30b8d52c7a189ebf5ab52421f
  Skia args: is_official_build=true is_debug=false skia_enable_gpu=true skia_enable_skottie=false skia_use_gl=true skia_use_egl=false skia_use_x11=false skia_use_system_libpng=false 
skia_use_libwebp_encode=false skia_use_libwebp_decode=false skia_use_system_zlib=false skia_use_xps=false skia_use_dng_sdk=false cc="clang" cxx="clang++" skia_use_direct3d=true 
skia_enable_skshaper=true skia_use_icu=true skia_use_system_icu=false skia_use_harfbuzz=true skia_pdf_subset_harfbuzz=true skia_use_system_harfbuzz=false skia_use_sfntly=false 
skia_enable_skparagraph=true skia_use_system_libjpeg_turbo=false win_vc="C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC" clang_win="C:\Program Files (x86)\Microsoft Visual 
Studio\2019\BuildTools\VC\Tools\Llvm\x64" target_cpu="x86_64" skia_use_expat=true skia_use_system_expat=false extra_cflags=["/MT","--target=x86_64-pc-windows-msvc"] 
extra_asmflags=["--target=x86_64-pc-windows-msvc"]
  Done. Made 90 targets from 43 files in 1820ms
  ninja: Entering directory `C:\j\skia\target\release\build\skia-bindings-ab470fb09135d076\out\skia'
  [1/1444] stamp obj/compile_sksl_spirv_tests.stamp
  [2/1444] stamp obj/armv7.stamp
  [3/1444] stamp obj/android_utils.stamp
  [4/1444] stamp obj/compile_sksl_glsl_nosettings_tests.stamp
  [5/1444] stamp obj/compile_sksl_metal_tests.stamp
  [6/1444] stamp obj/compile_sksl_glsl_tests.stamp
  [7/1444] stamp obj/compile_sksl_skvm_tests.stamp
  [8/1444] stamp obj/arm64.stamp
  [9/1444] stamp obj/fontmgr_android.stamp
  [10/1444] stamp obj/dehydrate_sksl.stamp
  [11/1444] stamp obj/crc32.stamp
  [12/1444] stamp obj/fontmgr_FontConfigInterface.stamp
  [13/1444] stamp obj/fontmgr_custom_directory.stamp
  [14/1444] stamp obj/fontmgr_custom_empty.stamp
  [15/1444] stamp obj/fontmgr_fontconfig.stamp
  [16/1444] stamp obj/fontmgr_custom_embedded.stamp
  [17/1444] stamp obj/fontmgr_fuchsia.stamp
  [18/1444] stamp obj/fontmgr_mac_ct.stamp
  [19/1444] compile ../../../../../../../../.cargo/git/checkouts/rust-skia-a9a1bb4afc362467/9010281/skia-bindings/skia/src/fonts/SkFontMgr_indirect.cpp
  ...
  [930/1444] copy ../../../../../../../../.cargo/git/checkouts/rust-skia-a9a1bb4afc362467/9010281/skia-bindings/skia/third_party/externals/icu/common/icudtl.dat icudtl.dat
  FAILED: icudtl.dat 
  cmd.exe /c  python3 "C:/.cargo/git/checkouts/rust-skia-a9a1bb4afc362467/9010281/skia-bindings/skia/gn/cp.py" 
../../../../../../../../.cargo/git/checkouts/rust-skia-a9a1bb4afc362467/9010281/skia-bindings/skia/third_party/externals/icu/common/icudtl.dat icudtl.dat
  'python3' is not recognized as an internal or external command,
  operable program or batch file.
  [931/1444] compile ../../../../../../../../.cargo/git/checkouts/rust-skia-a9a1bb4afc362467/9010281/skia-bindings/skia/third_party/externals/libjpeg-turbo/jdmaster.c
  [932/1444] compile ../../../../../../../../.cargo/git/checkouts/rust-skia-a9a1bb4afc362467/9010281/skia-bindings/skia/third_party/externals/spirv-cross/spirv_msl.cpp
  ninja: build stopped: subcommand failed.

  --- stderr
  Checking for "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\Llvm\\x64\\bin\\clang-cl.exe"
  thread 'main' panicked at '`ninja` returned an error, please check the output for details.', 
C:\.cargo\git\checkouts\rust-skia-a9a1bb4afc362467\9010281\skia-bindings\build_support\skia\config.rs:439:5
  stack backtrace:
     0:     0x7ff6f43f3a6f - std::backtrace_rs::backtrace::dbghelp::trace
                                 at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library\std\src\..\..\backtrace\src\backtrace\dbghelp.rs:98
     1:     0x7ff6f43f3a6f - std::backtrace_rs::backtrace::trace_unsynchronized
                                 at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library\std\src\..\..\backtrace\src\backtrace\mod.rs:66
     2:     0x7ff6f43f3a6f - std::sys_common::backtrace::_print_fmt
                                 at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library\std\src\sys_common\backtrace.rs:66
     3:     0x7ff6f43f3a6f - std::sys_common::backtrace::_print::impl$0::fmt
                                 at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library\std\src\sys_common\backtrace.rs:45
     4:     0x7ff6f441868a - core::fmt::write
                                 at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library\core\src\fmt\mod.rs:1196
     5:     0x7ff6f43ea0e9 - std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
                                 at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library\std\src\io\mod.rs:1654
     6:     0x7ff6f43f66eb - std::sys_common::backtrace::_print
                                 at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library\std\src\sys_common\backtrace.rs:48
     7:     0x7ff6f43f66eb - std::sys_common::backtrace::print
                                 at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library\std\src\sys_common\backtrace.rs:35
     8:     0x7ff6f43f66eb - std::panicking::default_hook::closure$1
                                 at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library\std\src\panicking.rs:295
     9:     0x7ff6f43f62de - std::panicking::default_hook
                                 at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library\std\src\panicking.rs:314
    10:     0x7ff6f43f6ce1 - std::panicking::rust_panic_with_hook
                                 at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library\std\src\panicking.rs:698
    11:     0x7ff6f43f6b62 - std::panicking::begin_panic_handler::closure$0
                                 at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library\std\src\panicking.rs:586
    12:     0x7ff6f43f4627 - std::sys_common::backtrace::__rust_end_short_backtrace<std::panicking::begin_panic_handler::closure_env$0,never$>
                                 at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library\std\src\sys_common\backtrace.rs:138
    13:     0x7ff6f43f6879 - std::panicking::begin_panic_handler
                                 at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library\std\src\panicking.rs:584
    14:     0x7ff6f4443075 - core::panicking::panic_fmt
                                 at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library\core\src\panicking.rs:142
    15:     0x7ff6f3c6114e - build_script_build::build_support::skia::config::configure_skia::{{closure}}::h1b68a3680743fa52
    16:     0x7ff6f3c60221 - build_script_build::build_support::skia::config::build::ha9855906cefd8355
    17:     0x7ff6f3c754e9 - build_script_build::build_support::xcode::get_sdk_path::h4242d5c407fc8024
    18:     0x7ff6f3c75933 - build_script_build::build_support::xcode::get_sdk_path::h4242d5c407fc8024
    19:     0x7ff6f3c65106 - core::ops::function::FnOnce::call_once::h17107a2aa6038a4b
    20:     0x7ff6f3c79a87 - std::sys_common::backtrace::__rust_begin_short_backtrace::h910d3a211830b5cd
    21:     0x7ff6f3c56a0c - std::rt::lang_start::{{closure}}::h469e3f26253d7030
    22:     0x7ff6f43e3a51 - core::ops::function::impls::impl$2::call_once
                                 at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc\library\core\src\ops\function.rs:280
    23:     0x7ff6f43e3a51 - std::panicking::try::do_call
                                 at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library\std\src\panicking.rs:492
    24:     0x7ff6f43e3a51 - std::panicking::try
                                 at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library\std\src\panicking.rs:456
    25:     0x7ff6f43e3a51 - std::panic::catch_unwind
                                 at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library\std\src\panic.rs:137
    26:     0x7ff6f43e3a51 - std::rt::lang_start_internal::closure$2
                                 at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library\std\src\rt.rs:128
    27:     0x7ff6f43e3a51 - std::panicking::try::do_call
                                 at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library\std\src\panicking.rs:492
    28:     0x7ff6f43e3a51 - std::panicking::try
                                 at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library\std\src\panicking.rs:456
    29:     0x7ff6f43e3a51 - std::panic::catch_unwind
                                 at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library\std\src\panic.rs:137
    30:     0x7ff6f43e3a51 - std::rt::lang_start_internal
                                 at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library\std\src\rt.rs:128
    31:     0x7ff6f3c569f0 - std::rt::lang_start::hf46f7f0de4c1a7b7
    32:     0x7ff6f3c76166 - main
    33:     0x7ff6f4433130 - invoke_main
                                 at d:\agent\_work\4\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
    34:     0x7ff6f4433130 - __scrt_common_main_seh
                                 at d:\agent\_work\4\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
    35:     0x7ffd1fb27974 - BaseThreadInitThunk
    36:     0x7ffd2191a2f1 - RtlUserThreadStart
```

**Comment by ctrlcctrlv** [comment] 2022-07-10 00:05
Sounds like a problem with the Choco package.

Creating a link from python3 to python is required, on Unix it can be further tweaked by something like `update-alternatives`.

**Comment by Kethku** [comment] 2023-09-15 22:44
I just installed python from the official installer and no python3 link was created. I know very little about python. Are these two executables different? There is a python3.dll but that isn't executable directly on windows.

This seems like a platform specific issue that should be fixed.

**Comment by pragmatrix** [comment] 2023-09-16 11:17
This was caused by a hardcoded invocations of `python3` in Skia's GN build scripts, even though we pass the probed executable to GN using `--script-executable`. I've changed that from `python3` to `python` where the `icudtl.dat` file is copied. The invoked script `cp.py` seems to be compatible with Python 2, so as long `python` exists in the path, the workaround in #838 should work.

**Closed** 2023-09-16 11:17 UTC
