### ISSUE TITLE
Build fails on x86_64-pc-windows-gnu

### ISSUE THREAD

**Issue by X1nto** [rust-skia/rust-skia#769] opened 2023-02-16 09:50 UTC
Trying to run `cargo build` on an `x86_64-pc-windows-gnu` platform installed with `rustup` results in the following error:
```
Compiling skia-bindings v0.58.0                                                                                                                 
error: failed to run custom build command for `skia-bindings v0.58.0`                                                                              

Caused by:
  process didn't exit successfully: `C:\Users\Xinto\CLionProjects\Crust\target\debug\build\skia-bindings-a5e42a77858f9d32\build-script-build` (exit code: 101)
  --- stdout
  cargo:rerun-if-env-changed=DOCS_RS
  cargo:rerun-if-env-changed=SKIA_DEBUG
  HOST: x86_64-pc-windows-gnu
  cargo:rerun-if-env-changed=SKIA_SOURCE_DIR
  cargo:rerun-if-env-changed=FORCE_SKIA_BUILD
  cargo:rerun-if-env-changed=FORCE_SKIA_BINARIES_DOWNLOAD
  TRYING TO DOWNLOAD AND INSTALL SKIA BINARIES: 0.58.0/3e3c012335c2258c0e10-x86_64-pc-windows-gnu
  cargo:rerun-if-env-changed=SKIA_BINARIES_URL
    FROM: https://github.com/rust-skia/skia-binaries/releases/download/0.58.0/skia-binaries-3e3c012335c2258c0e10-x86_64-pc-windows-gnu.tar.gz       
  DOWNLOAD AND INSTALL FAILED: https://github.com/rust-skia/skia-binaries/releases/download/0.58.0/skia-binaries-3e3c012335c2258c0e10-x86_64-pc-windows-gnu.tar.gz: status code 404
  STARTING A FULL BUILD
  cargo:rerun-if-env-changed=CLANGCC
  cargo:rerun-if-env-changed=CC
  cargo:rerun-if-env-changed=CLANGCXX
  cargo:rerun-if-env-changed=CXX
  HOST: x86_64-pc-windows-gnu
  cargo:rerun-if-env-changed=OPT_LEVEL
  cargo:rerun-if-env-changed=SKIA_USE_SYSTEM_LIBRARIES
  cargo:rerun-if-env-changed=SDKTARGETSYSROOT
  cargo:rerun-if-env-changed=SDKROOT
  HOST: x86_64-pc-windows-gnu
  cargo:rerun-if-env-changed=SKIA_NINJA_COMMAND
  cargo:rerun-if-env-changed=SKIA_GN_COMMAND
  Probing 'python'
  Python 3 found: "python"
  Synchronizing Skia dependencies
  DOWNLOADING: https://codeload.github.com/rust-skia/skia/tar.gz/m109-0.57.1
  DOWNLOADING: https://codeload.github.com/rust-skia/depot_tools/tar.gz/73a2624
  Skipping "bin".
  skia\third_party/externals/zlib      > c876c8f87101c5a75f6014b0f832499afeb65b73
  skia\third_party/externals/wuffs     > a0041ac0310b3156b963e2f2bea09245f25ec073
  skia\third_party/externals/piex      > bb217acdca1cc0c16b704669dd6f91a1b509c406
  ...rd_party/externals/d3d12allocator > 169895d529dfce00390a20e69c2f516066fe7a3b
  ...ird_party/externals/libjpeg-turbo > ed683925e4897a84b3bffc5c1414c85b97a129a3
  skia\third_party/externals/expat     > a28238bdeebc087071777001245df1876a11f5ee
  ...third_party/externals/spirv-cross > abc31207bffbc1bef4192746af44b3be1abcff17
  ...y/externals/vulkanmemoryallocator > 7de5cc00de50e71a3aab22dea52fbb7ff4efceb6
  skia\third_party/externals/libwebp   > a8e366166ab57bb1b4aaf6739fc775515bc71b51
  skia\third_party/externals/freetype  > 1bfaca0635d5c90fa6088dc01d99899a947b7d29
  skia\third_party/externals/brotli    > 6d03dfbedda1615c4cba1211f8d81735575209c8
  skia\third_party/externals/libpng    > 386707c6d19b974ca2e3db7f5c61873813c6fe44
  skia\third_party/externals/harfbuzz  > f1f2be776bcd994fa9262622e1a7098a066e5cf7
  skia\third_party/externals/icu       > a0718d4f121727e30b8d52c7a189ebf5ab52421f
  Skia args: is_official_build=true is_debug=false skia_enable_svg=false skia_enable_gpu=false skia_enable_skottie=false skia_enable_pdf=true skia_u
se_gl=false skia_use_egl=false skia_use_x11=false skia_use_system_libpng=false skia_use_libwebp_encode=false skia_use_libwebp_decode=false skia_use_
system_zlib=false skia_use_xps=false skia_use_dng_sdk=false cc="clang" cxx="clang++" skia_use_icu=false skia_use_harfbuzz=false skia_use_system_libj
peg_turbo=false skia_use_expat=true skia_use_system_expat=false target_os="win" target_cpu="x86_64" extra_cflags=["--target=x86_64-pc-windows-gnu"] extra_asmflags=["--target=x86_64-pc-windows-gnu"]
  ERROR at //gn/BUILDCONFIG.gn:131:14: Script returned non-zero exit code.
      win_vc = exec_script("//gn/find_msvc.py", [], "trim string")
               ^----------
  Current dir: C:/Users/Xinto/CLionProjects/Crust/target/debug/build/skia-bindings-b47e825f445ee3e2/out/skia/
  Command: C:/msys64/mingw64/bin/python.exe C:/Users/Xinto/.cargo/registry/src/github.com-1ecc6299db9ec823/skia-bindings-0.58.0/skia/gn/find_msvc.py
  Returned 1.

  --- stderr
  Traceback (most recent call last):
    File "C:\Users\Xinto\.cargo\registry\src\github.com-1ecc6299db9ec823\skia-bindings-0.58.0\skia\gn\find_msvc.py", line 36, in <module>
      result = find_msvc()
    File "C:\Users\Xinto\.cargo\registry\src\github.com-1ecc6299db9ec823\skia-bindings-0.58.0\skia\gn\find_msvc.py", line 29, in find_msvc
      paths = subprocess.check_output(command).decode('utf-8').splitlines()
    File "C:\msys64\mingw64\lib\python3.10\subprocess.py", line 421, in check_output
      return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
    File "C:\msys64\mingw64\lib\python3.10\subprocess.py", line 503, in run
      with Popen(*popenargs, **kwargs) as process:
    File "C:\msys64\mingw64\lib\python3.10\subprocess.py", line 971, in __init__
      self._execute_child(args, executable, preexec_fn, close_fds,
    File "C:\msys64\mingw64\lib\python3.10\subprocess.py", line 1440, in _execute_child
      hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
  FileNotFoundError: [WinError 2] The system cannot find the file specified
  thread 'main' panicked at '""', C:\Users\Xinto\.cargo\registry\src\github.com-1ecc6299db9ec823\skia-bindings-0.58.0\build_support\skia\config.rs:317:5
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Dependencies:
```toml
[dependencies]
skia-safe = "0.58.0"
```

**Comment by pragmatrix** [comment] 2023-02-17 18:40
Closed as duplicate of #345

**Closed by pragmatrix** 2023-02-17 18:40 UTC
