### ISSUE TITLE
draw_text_blob not working

### ISSUE THREAD

**Issue by toplinuxsir** [rust-skia/rust-skia#370] opened 2020-08-07 04:00 UTC
os: Ubuntu20.04 , rust 1.45.2
```
 let (paint1, paint2, paint3) = (
            &mut Paint::default(),
            &mut Paint::default(),
            &mut Paint::default(),
        );
        paint1
            .set_anti_alias(true)
            .set_color(Color::from_rgb(255, 0, 0))
            .set_style(MPaint::Style::Fill);
        paint2
            .set_anti_alias(true)
            .set_color(Color::from_rgb(0, 136, 0))
            .set_style(MPaint::Style::Stroke)
            .set_stroke_width(3.0);
        paint3
            .set_anti_alias(true)
            .set_color(Color::from_rgb(136, 136, 136));
        let blob1 = TextBlob::from_str(
            "Skia!",
            &Font::from_typeface_with_params(Typeface::default(), 90.0, 1.0, 0.0),
        )
        .unwrap();
        let blob2 = TextBlob::from_str(
            "Skia!",
            &Font::from_typeface_with_params(Typeface::default(), 64.0, 1.5, 0.0),
        )
        .unwrap();

        let fill_paint = &mut Paint::default();
        let stroke_paint = &mut Paint::default();
        stroke_paint
            .set_style(MPaint::Style::Stroke)
            .set_stroke_width(3.0);
        let mut _canvas = self
            .surface
            .canvas()
            .clear(Color::WHITE)
            .draw_text_blob(&blob1, (20.0, 64.0), paint1)
            .draw_text_blob(&blob1, (20.0, 144.0), paint2)
            .draw_text_blob(&blob2, (20.0, 224.0), paint3)
```
save the canvas to png file ,but the text not show,

**Comment by pragmatrix** [comment] 2020-08-07 05:45
I've copied your code into the skia-org/ example and run it with --driver opengl and --driver cpu on an Ubuntu 20 VM with just the expected result. To continue, I'll have to ask for a full repro, because I assume that it has more to do what backend you use, how the surface is set up, or how the image is saved.

**Comment by toplinuxsir** [comment] 2020-08-07 07:30
@pragmatrix 
```
   let mut surface = Surface::new_raster_n32_premul((width, height)).expect("no surface!");

    #[inline]
    pub fn data(&mut self) -> Data {
        let image = self.surface.image_snapshot();
        image.encode_to_data(EncodedImageFormat::PNG).unwrap()
    }

```

**Comment by pragmatrix** [comment] 2020-08-07 09:18
This is exactly what the skia-org/ in this repository does. I've also modified it so that it pulls the prebuilt binaries (assuming that you did not build it from master), and so far the images are generated on my Ubuntu VM. To continue, please either provide a full repo (a complete cargo project), or try to see if the /skia-org example from the master branch works for you (to use the prebuilt binaries, you need to copy the project out of the workspace and change the skia-safe reference to `skia-safe="0"`).

**Comment by pragmatrix** [comment] 2020-08-20 11:32
@toplinuxsir I am closing this, please reopen if you can provide a project able to reproduce the problem.

**Closed by pragmatrix** 2020-08-20 11:32 UTC
Labels: bug, needs repro
