### ISSUE TITLE
Canvas.draw_path memory usage high with Metal

### ISSUE THREAD

**Issue by triniwiz** [rust-skia/rust-skia#308] opened 2020-04-01 10:29 UTC
So in my iOS lib I have a GL and a Metal renderer   in my last round of testing using a Metal surface noticed `.draw_path` has a higher memory usage that keep climbing until the app crashes but if I swap to gl it’s fine (maintains ~80 MB)

if you’re wondering what I’m drawing is a couple hundred particles even if I use ~5 the usage would be high enough to crash

![3DDDCADC-D3BC-478A-AEBF-678925547C2F](https://user-images.githubusercontent.com/6695919/78130348-298d7f00-73e7-11ea-9a43-b2bb2fb73f1c.png)

[Animation](https://i.imgur.com/hiR7zdL.gifv)

**Comment by pragmatrix** [comment] 2020-04-02 07:35
This might be a problem in Skia. Last time I checked, the Metal rendering is beta, and since OpenGL does not exhibit this problem, it may be a problem in the implementation. 

Also you might check if the cache limits are used up and could be changed in `gpu::Context`, may be calling `free_gpu_resources()` could be used to get an initial indication if that is the problem. 

Flutter fixed a similar incident before: https://github.com/flutter/engine/pull/9503

If I can free some time over the next days I am trying to reproduce the memory leak on macOS with Meta.

BTW: I love that demo!

**Comment by triniwiz** [comment] 2020-04-02 07:51
Thanks for the link also something I noticed if I increase the particles in my demos it will slow things down [e.g](https://imgur.com/a/d27ynUw) you won’t see it here but let’s say I tap the screen a bit faster so it would produce more particles (I think 50 per tap) (draw_path) it will eventually slow down 🙂 .. happens on gl also it just takes a bit more jamming (pressure)

**Comment by pragmatrix** [comment] 2020-04-19 10:15
I was able to reproduce this memory leak on macOS/Metal by just repeatedly drawing a path and flushing the canvas. But when I wrap both calls into an AutoreleasePool the problem disappears, so I guess that Skia does allocate cocoa autorelease objects behind the scenes. Related: #319

**Comment by pragmatrix** [comment] 2020-04-27 13:23
I am closing this, please reopen if memory leaks persists after adding another AutoreleasePool.

@triniwiz The slowdown could have a number of issues, but I am guessing that path rendering is just not that fast. If the slowdown persists even when there are less particles on screen afterwards, it would be worth to investige further.

**Closed by pragmatrix** 2020-04-27 13:24 UTC
Labels: api ergonomics, target:ios

**Comment by jthomas-dd** [comment] 2022-10-25 03:36
@pragmatrix 

I'm trying to make use of Metal, but also have run into a memory leak.

I've tried wrapping the call with autorelease_pool, but I'm still  seeing a very large multiple hundred megabyte per second leak when rendering at a normal framerate (30fps).

In this case it reproduces when calling any of the `draw_image` functions, and only while using the Metal backend.

https://github.com/jthomas-dd/skia-safe-metal-leak

I've provided a demo which detects memory differences between `draw_image` calls.

When using a software backend, the memory difference while drawing is virtually identical. When using Metal it leaks over 500MB before the test finishes, and asserts failure.

<img width="1488" alt="image" src="https://user-images.githubusercontent.com/97064632/197676510-9a02c3ab-8235-4ebb-97ec-efced0311041.png">

**Comment by thedracle** [comment] 2022-10-25 15:34
Spent some time adding in some charts to demonstrate the leak situation:
![image](https://user-images.githubusercontent.com/1301817/197817135-e957b73d-d119-4a38-a8c7-0b21f2c7aabb.png)

I'm going to try fiddling around, I suspect it may be leaking 1 image per render, and maybe it's because of wrapping a SkImage around my buffer per frame.

Probably this is API misusage somehow, but it would be great to know/document how.

**Comment by jthomas-dd** [comment] 2022-10-25 16:13
It seems that recreating the Image object is the root cause:

https://github.com/jthomas-dd/skia-safe-metal-leak/commit/5ee1db1957adff4db44d5c48d80183e975f81794

I am using new_bytes:
src/core/data.rs:78
```
    pub unsafe fn new_bytes(data: &[u8]) -> Self {
        Data::from_ptr(sb::C_SkData_MakeWithoutCopy(data.as_ptr() as _, data.len())).unwrap()
    }
```

Which looks like it's just a wrapper around the pointer I've passed it, that expects the underlying data to outlive this image.

It then uses `from_raster_data`:
src/core/image.rs:52
```
    pub fn from_raster_data(
        info: &ImageInfo,
        pixels: impl Into<Data>,
        row_bytes: usize,
    ) -> Option<Image> {
        Image::from_ptr(unsafe {
            sb::C_SkImage_MakeRasterData(info.native(), pixels.into().into_ptr(), row_bytes)
        })
    }
```

It's surrounded by an autoreleasepool, and doesn't have a lifetime outside of the drawing function, so I would expect it should be released.

Regardless I can confirm reusing the image resolves the severe leak in this circumstance, but I have a need to resize/change the Image, and I suspect there will still be a leak every time I switch out the Image for a new one.

**Comment by thedracle** [comment] 2022-10-25 22:26
Unfortunately I've confirmed that the SkImage remains static when rendered indefinitely in the case which doesn't leak, which I guess should be obvious.

I switched to creating a Surface, using write_pixels_from_pixmap, and drawing the resulting image, and the leak is back in force 😢 

```
            let image = if let Some(mut image) = image {
                if image.width() as u32 != *w || image.height() as u32 != *h {
                    // Recreate from raster if dimensions change.
                    surface_from_pixels(pixels, info, *w)
                } else {
                    let pixmap = pixmap_from_raster(pixels, info, *w);
                    image.write_pixels_from_pixmap(&pixmap, (0, 0));
                    Some(image)
                }
            } else {
                surface_from_pixels(pixels, info, *w)
            };
            let image = if let Some(mut image) = image {
                let sk_image = image.image_snapshot();
                let result = canvas.draw_image_scale(&sk_image, *x, *y, scale);
                event!(Level::TRACE, "Draw image scale: {}", result);
                Some(image)
            } else {
                event!(Level::ERROR, "Failed to create image from raster data.");
                None
            };
```

Ultimately I am reading changing buffers of pixels from a video file, and I want to compose and scale them into a combined surface, hopefully leveraging Metal in the backend.

Any help on the correct (non-leaky) way to perform the above effect would be greatly appreciated.

**Comment by jthomas-dd** [comment] 2022-10-25 22:54
Switching to using a metal Surface for generating the image moves the leak to:
```
image.write_pixels_from_pixmap(&pixmap, (0, 0));
```

Calling `context.free_gpu_resources();` resolves the leak, so it must be GPU resources being allocated in the background per render?

Is this just something normal for the Metal backend?
