### ISSUE TITLE
Support Alpine / musl

### ISSUE THREAD

**Issue by arraypad** [rust-skia/rust-skia#356] opened 2020-07-24 23:21 UTC
At the moment skia-bindings/build_support/skia.rs targets GNU libc explicitly for Linux.

If I remove that restriction (or add `(_, "unknown", "linux", Some("musl"))`):
```diff --git a/skia-bindings/build_support/skia.rs b/skia-bindings/build_support/skia.rs
index 2133300..dfc1812 100644
--- a/skia-bindings/build_support/skia.rs
+++ b/skia-bindings/build_support/skia.rs
@@ -372,7 +372,7 @@ impl BinariesConfiguration {
         let mut link_libraries = Vec::new();
 
         match target.as_strs() {
-            (_, "unknown", "linux", Some("gnu")) => {
+            (_, "unknown", "linux", _) => {
                 link_libraries.extend(vec!["stdc++", "fontconfig", "freetype"]);
                 if features.gl {
                     link_libraries.push("GL");
```

...and install ninja and gn via apk, and convince the build to use them rather than from downloaded deps:
```
RUN git clone --depth 1 --single-branch --branch m84-0.30.1 https://github.com/rust-skia/skia.git /skia
ENV SKIA_OFFLINE_SOURCE_DIR=/skia \
	SKIA_OFFLINE_NINJA_COMMAND=/usr/bin/ninja \
	SKIA_OFFLINE_GN_COMMAND=/usr/bin/gn
```

...and build with `-crt-static`:
```
ENV RUSTFLAGS="-C target-feature=-crt-static"
```

...then it all works ok!

It would be helpful for me, and I imagine for others, if rust-skia could support Alpine/musl out of the box.
I know there's a risk in conflating Alpine and musl, but it's handy in this case that Alpine has packages for gn and ninja. Maybe the branch matching the musl ABI is conditional on having those executables in the PATH already?

I can spend a bit more time to whittle down my Dockerfile to a minimal reproduction if that's helpful, let me know.

FWIW the size of my docker image using rust-skia went from 145MB based on debian:10-slim to 63MB using alpine:3.12.0

**Comment by pragmatrix** [comment] 2020-08-04 14:33
I'd really like to support more target platforms.

But assuming that you mean with "support", support in the sense that binaries are built and released, I am a bit hesitant to add more platform targets, specifically when they can not be built on the hosts we already support (I've tried to build a musl binary from a Ubuntu 20 distribution, but failed so far).

This hesitation is rooted by the fact that we run the CI and build the binaries on Azure while the world around us is moving to [GitHub Actions](https://github.com/features/actions) and I don't like to invest in tools that have their end of "proper support" appearing on the horizon. So to continue, we'll have to first port the CI build scripts To GitHub Actions, which [I've tried here a few days ago](https://github.com/pragmatrix/rust-skia/pull/8). And while the builds on the host platforms seem to work, there is [one feature needed](https://github.com/actions/runner/issues/438) before we can consider building non-host targets or even docker based builds.

For now, I would be glad if you could provide a PR that would make it possible to build musl right after checking out the repository. It's also a great suggestion to run gn and ninja from the PATH if the host platform isn't one depot_tools downloads binaries for.

**Comment by arraypad** [comment] 2020-08-11 22:29
Ok thanks for the clear explanation - I totally get that. I didn't mean to suggest building binaries for this triplet but only because that hadn't occurred to me. That's a nice idea and I'd like to help.

Also nice to see the feature needed seems to have landed!

My time is pretty limited at the moment but I'll follow up with a PR or two.

**Comment by pragmatrix** [comment] 2020-09-10 06:38
**Update**. Because of a ciritical problem with the `libstdc++` dependency, containers are used to build the Linux binaries #406, which means that we could attempt to fully support Apine with musl builds and binaries.

To continue, we would need the patch above as a PR, and a Dockerfile that prepares the image similar to https://github.com/pragmatrix/rust-skia-containers/blob/master/Dockerfile.

**Comment by wanming** [comment] 2022-05-24 10:56
@arraypad I tried your way but failed on rust:1.60.0-alpine3.15，the log is here: 

Compiling skia-bindings v0.50.0
error: failed to run custom build command for `skia-bindings v0.50.0`

Caused by:
  process didn't exit successfully: `/Users/tom/Projects/emfio/target/debug/build/skia-bindings-cfbd42c2e598fa3c/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-env-changed=SKIA_DEBUG
  cargo:rerun-if-env-changed=SKIA_SOURCE_DIR
  cargo:rerun-if-env-changed=FORCE_SKIA_BUILD
  cargo:rerun-if-env-changed=FORCE_SKIA_BINARIES_DOWNLOAD
  TRYING TO DOWNLOAD AND INSTALL SKIA BINARIES: 0.50.0/d56593c5d9f3d69ad90b-aarch64-unknown-linux-musl
  cargo:rerun-if-env-changed=SKIA_BINARIES_URL
    FROM: https://github.com/rust-skia/skia-binaries/releases/download/0.50.0/skia-binaries-d56593c5d9f3d69ad90b-aarch64-unknown-linux-musl.tar.gz
  DOWNLOAD AND INSTALL FAILED: https://github.com/rust-skia/skia-binaries/releases/download/0.50.0/skia-binaries-d56593c5d9f3d69ad90b-aarch64-unknown-linux-musl.tar.gz: status code 404
  STARTING A FULL BUILD
  HOST: aarch64-unknown-linux-musl
  cargo:rerun-if-env-changed=OPT_LEVEL
  cargo:rerun-if-env-changed=CC
  cargo:rerun-if-env-changed=CXX
  cargo:rerun-if-env-changed=SKIA_USE_SYSTEM_LIBRARIES
  cargo:rerun-if-env-changed=SDKROOT
  cargo:rerun-if-env-changed=SKIA_NINJA_COMMAND
  cargo:rerun-if-env-changed=SKIA_GN_COMMAND
  Probing 'python'
  Python 2 found: "python"
  Skia args: is_official_build=true is_debug=false skia_enable_gpu=false skia_enable_skottie=false skia_use_gl=false skia_use_egl=false skia_use_x11=false skia_use_system_libpng=true skia_use_libwebp_encode=false skia_use_libwebp_decode=false skia_use_system_zlib=true skia_use_xps=false skia_use_dng_sdk=false cc="clang" cxx="clang++" skia_use_icu=false skia_use_system_libjpeg_turbo=true target_os="linux" target_cpu="arm64" skia_use_expat=true skia_use_system_expat=true extra_cflags=["-O0","--target=aarch64-unknown-linux-musl"] extra_asmflags=["--target=aarch64-unknown-linux-musl"]
  Done. Made 79 targets from 33 files in 263ms
  ninja-built-libraries: ["skia"], config.otput_directory: /Users/tom/Projects/emfio/target/debug/build/skia-bindings-bc6e326ca4e235ba/out/skia

  --- stderr
  ninja: open build.ninja: No such file or directory
  thread 'main' panicked at '`ninja` returned an error, please check the output for details.', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/skia-bindings-0.50.0/build_support/skia/config.rs:418:5
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


it looks like some args in ninja was wrong, but I don't know why. can you give me some hint?

**Comment by wanming** [comment] 2022-05-25 07:23
@arraypad 
<img width="1408" alt="image" src="https://user-images.githubusercontent.com/1776500/170203497-95156cd7-a5c0-4bf2-81aa-5475278e70eb.png">
HI，I follow your steps and got this error, I'm trying to build my repo (it's using `skia-safe 0.50.0` as its deps) on docker image `rust:1.60.0-alpine3.15` on my macOS M1，it seems like gn command failed, but I can find the build.ninja in the folder. Can you give me some help? here is my steps in docker container:

```bash
apk add curl bash gcc llvm clang python2 git ninja musl-dev  g++ vim  linux-headers 
git clone https://gn.googlesource.com/gn /tmp/gn 
git -C /tmp/gn checkout dfcbc6fed0a8352696f92d67ccad54048ad182b3 
cd /tmp/gn 
python build/gen.py 
ninja -C out 
cp -f /tmp/gn/out/gn /usr/local/bin/gn
cd /my-repo-dir 
# RUSTFLAGS=-Ctarget-feature=-crt-static SKIA_GN_COMMAND=gn SKIA_NINJA_COMMAND=ninja  cargo build -vv
```

thanks very much

**Closed** 2022-06-06 19:44 UTC
Labels: enhancement, build
