### ISSUE TITLE
Unable to build skia

### ISSUE THREAD

**Issue by redfurever** [rust-skia/rust-skia#687] opened 2022-09-02 12:26 UTC
I seem to be getting this error and i have no idea how to fix it. I have ninja, llvm isntalled as well
![image](https://user-images.githubusercontent.com/62601155/188142389-1893205d-b907-47c7-9fc4-0d2871c75e19.png)

**Comment by redfurever** [comment] 2022-09-02 12:32
![image](https://user-images.githubusercontent.com/62601155/188143295-ebedd448-8e47-43d5-a38b-d972b191c6bd.png)
this is where it failed

**Comment by pragmatrix** [comment] 2022-09-02 13:04
Hello, thank you for the report. I suspect that this is a duplicate of #314:

> A workaround is to move the source directory to the same drive as your rust installation, or vice versa.

**Closed by pragmatrix** 2022-09-02 13:04 UTC
