### ISSUE TITLE
failed to run custom build command for skia-bindings

### ISSUE THREAD

**Issue by gasacchi** [rust-skia/rust-skia#454] opened 2021-01-07 11:56 UTC
Hi, i try to build neovide https://github.com/Kethku/neovide, which use skia-bindings.
I currently use Void linux musl version, and got this:
```
error: failed to run custom build command for `skia-bindings v0.32.1`

Caused by:
  process didn't exit successfully: `/home/gasacchi/xxx/.dev/clone/neovide/target/release/build/skia-bindings-9eeb30d52802e4e0/build-script-build` (signal: 11, SIGSEGV: invalid memory reference)

```

**Comment by pragmatrix** [comment] 2021-01-10 19:18
There are no prebuilt binaries of rust-skia available yet for musl targets (yet) and a full build will probably fail because the executable `skia-bindings/skia/bin/gn` will not run. See #356 for more information.

One way to move forward here is to get the master branch to cross compile to musl, and then try to see if the generated binaries can be used in a musl distribution.

That said, the segfault is unexpected and perhaps even unrelated. Can you to build neovide with `cargo build -vv` to see when exactly that happens?

**Comment by gasacchi** [comment] 2021-01-11 09:39
maybe i will try it later on, btw this is some last line when build neovide with -vv
```

 Compiling skia-bindings v0.32.1
       Fresh futures-executor v0.3.8
     Running `/home/gasacchi/xxx/.dev/clone/neovide/target/release/build/skia-bindings-9eeb30d52802e4e0/build-script-build`
       Fresh jpeg-decoder v0.1.20
       Fresh wayland-protocols v0.23.6
       Fresh sdl2-sys v0.34.3
       Fresh lru v0.4.3
       Fresh skribo v0.1.0 (https://github.com/linebender/skribo#a35c876b)
       Fresh futures v0.3.8
       Fresh smithay-client-toolkit v0.6.6
       Fresh sdl2 v0.34.3
       Fresh image v0.22.5
       Fresh nvim-rs v0.1.1-alpha.0 (https://github.com/kethku/nvim-rs#109feea9)
       Fresh crossfire v0.1.4
       Fresh winit v0.22.2
error: failed to run custom build command for `skia-bindings v0.32.1`

Caused by:
  process didn't exit successfully: `/home/gasacchi/xxx/.dev/clone/neovide/target/release/build/skia-bindings-9eeb30d52802e4e0/build-script-build` (signal: 11, SIGSEGV: invalid memory reference)

````
every thing except skia-bindings is compiled

**Comment by pragmatrix** [comment] 2021-03-10 17:46
I've managed to build Dockerfile and build Skia in a voidlinux-musl docker container. But hit a showstopper on the binding generation:

```
 thread 'main' panicked at 'Unable to find libclang: "the `libclang` shared library at /usr/lib64/libclang.so.11 could not be opened: Dynamic loading not supported"', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.57.0/src/lib.rs:1975:31
```

Updated Dockerfile is [here](https://github.com/rust-skia/rust-skia/blob/master/docker/voidlinux-musl/Dockerfile).

I am closing this issue, because I can't reproduce the SIGSEGV "invalid memory reference" and mut assume that it is not related to rust-skia.

**Closed by pragmatrix** 2021-03-10 17:46 UTC
